Test

diff --git a/.github/workflows/azure-static-web-apps-wonderful-mushroom-04118a203.yml b/.github/workflows/azure-static-web-apps-wonderful-mushroom-04118a203.yml
--- a/.github/workflows/azure-static-web-apps-wonderful-mushroom-04118a203.yml
+++ b/.github/workflows/azure-static-web-apps-wonderful-mushroom-04118a203.yml
@@ -2,6 +2,7 @@ name: BooKeeper Azure Static Web Apps CI/CD
 
 env:
   KV_NAME: bookeeper-kv
+  DB_SERVER_NAME: BooKeeper-dbs
 
 on:
   push:
@@ -13,24 +14,24 @@ on:
       - main
 
 jobs:
-  deploy_resources_job:
-    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
-    runs-on: ubuntu-latest
-    name: Deploy Azure Resources
-    steps:
-      - uses: actions/checkout@main
-      - name: azure login
-        uses: azure/login@v1
-        with:
-          creds: ${{ secrets.AZURE_SP_CREDENTIALS }}
-      - name: deploy bicep file
-        uses: azure/arm-deploy@v1
-        with:
-          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
-          template: ./Bicep/main.bicep
-          parameters: ./Bicep/main.parameters.json adminLoginName=${{ secrets.AZURE_DB_ADMIN_NAME }} adminLoginPassword=${{ secrets.AZURE_DB_ADMIN_PASSWORD }}
-          failOnStdErr: false
+  # deploy_resources_job:
+  #   if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
+  #   runs-on: ubuntu-latest
+  #   name: Deploy Azure Resources
+  #   steps:
+  #     - uses: actions/checkout@main
+  #     - name: azure login
+  #       uses: azure/login@v1
+  #       with:
+  #         creds: ${{ secrets.AZURE_SP_CREDENTIALS }}
+  #     - name: deploy bicep file
+  #       uses: azure/arm-deploy@v1
+  #       with:
+  #         subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+  #         resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
+  #         template: ./Bicep/main.bicep
+  #         parameters: ./Bicep/main.parameters.json adminLoginName=${{ secrets.AZURE_DB_ADMIN_NAME }} adminLoginPassword=${{ secrets.AZURE_DB_ADMIN_PASSWORD }}
+  #         failOnStdErr: false
 
   build_and_deploy_job:
     needs: deploy_resources_job
@@ -49,26 +50,36 @@ jobs:
           keyvault: "bookeeper-kv"
           secrets: "webAppApiKey, dbConnectionString"
         id: myGetSecretAction  
+      - name: Public IP
+        id: ip
+        uses: haythem/public-ip@v1.3
+
+      - name: Add IP to database whitelist
+        uses: azure/CLI@v1
+        with:
+          azcliversion: 2.42.0
+          inlineScript: |
+            az sql server firewall-rule create --resource-group rg-bookeeper --server BooKeeper-dbs --name PipelineRule --start-ip-address ${{ steps.ip.outputs.ipv4 }} --end-ip-address ${{ steps.ip.outputs.ipv4 }}
       - name: Build Migration project
         working-directory: ./BooKeeperWebApp.Database.Migration
         run: dotnet build --configuration Release
-      - name: script
-        run: bash ./Scripts/FolderTree.sh ./
+      # - name: script
+      #   run: bash ./Scripts/FolderTree.sh ./
       - name: Migrate database
         working-directory: ./BooKeeperWebApp.Database.Migration
         env:
           ConnectionStrings:DefaultConnection: ${{ steps.myGetSecretAction.outputs.dbConnectionString }}
         run: dotnet run
-      - name: Build And Deploy
-        id: builddeploy
-        uses: Azure/static-web-apps-deploy@v1
-        with:
-          azure_static_web_apps_api_token: ${{ steps.myGetSecretAction.outputs.webAppApiKey }}
-          repo_token: ${{ secrets.GITHUB_TOKEN }}
-          action: "upload"
-          app_location: "Client"
-          api_location: "Api"
-          output_location: "wwwroot"
+      # - name: Build And Deploy
+      #   id: builddeploy
+      #   uses: Azure/static-web-apps-deploy@v1
+      #   with:
+      #     azure_static_web_apps_api_token: ${{ steps.myGetSecretAction.outputs.webAppApiKey }}
+      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
+      #     action: "upload"
+      #     app_location: "Client"
+      #     api_location: "Api"
+      #     output_location: "wwwroot"
 
   close_pull_request_job:
     if: github.event_name == 'pull_request' && github.event.action == 'closed'
